### ISSUE TITLE
Q: What do you think about implement layer depth logic?

### ISSUE THREAD

**Issue by Valexr** [crinklesio/feo-css#3]
Tx for good ideas 👍🏻 I opened new(old) world today when reading yours articles🤓

What do you think about implement layer depth logic with colour differentiation?

I’m experimented with other scss framework spectre.css (maybe you know)… & it’s haven’t darkened & depths color logic… & I trying add this something like:

```html
<div class="deps deps-background">
```

![7AD695EA-7286-40D7-8712-8F437E750329](https://user-images.githubusercontent.com/5656366/124502207-b2a21b80-ddcb-11eb-8aeb-3922aff9fda0.jpeg)

**Comment by thecrinkles** [comment]
If I understand your question correctly, you could achieve this by using `rgba` or `hsla` values when defining colors in the `$feo-colors` array. This can be achieved by hand, you you can write a function that generates the array for based on some settings? You could have a black background with light colors with a small opacity, to create the effect you have in the image. 

If you don't want to work with opacity hex values, you could go with `hsl` where you keep the `h` and `s` the same, but generate an array of values where the `l` changes. Below is for instance the grayscale color palette I use on my personal website. Although its just 4 colors, it shows how you can be in the same tone.

```scss
$h: 218;
$s: 25%;

$feo-colors: (
  'gray-100': hsl($h, $s, 98%),
  'gray-200': hsl($h, $s, 70%),
  'gray-300': hsl($h, $s, 18%),
  'gray-400': hsl($h, $s, 9%),
);
```

Is that you are looking for?

**Comment by Valexr** [comment]
Yep, it’s understood. I’m using now same logic.
And how I can generate classes by tokens in theme & this approach need mixin in class:

```css
.deps {
   color: var(--color);
   background-color: var(--back);
}
```

P.s. transparency logic not useful with overlaying layers…

**Comment by Valexr** [comment]
Just for example color-layer-depth logic...

In dark mode :hover, :focus element color lighter then background color
<img width="250" src="https://user-images.githubusercontent.com/5656366/126859055-e75f0df7-b0b0-48dd-80ea-a6b0133a72c8.jpg" />

In light mode :hover, :focus element color darker then background color
<img width="250" src="https://user-images.githubusercontent.com/5656366/126859058-2a5bc987-de0d-4f56-8363-1df79c692770.jpg" />

But for true logic mast be lighter then background color
<img width="250" src="https://user-images.githubusercontent.com/5656366/126859057-4fc22163-6803-412f-ae9e-10153eb77699.jpg" />
